{{- if .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "mongodb.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - get
    resourceNames:
      - {{ include "mongodb.fullname" . }}-config
  - apiGroups: [""]
    resources: ["pods"]
    verbs:
      - get
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mongodb.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "mongodb.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "mongodb.fullname" . }}-role
{{- end }}