{{- if .Values.serviceAccount.create }}
{{/*
Service Accounts for the MongoDB database pods
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mongodb.serviceAccountName" . }}
  labels:
    {{- include "mongodb.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}