{{- if and .Values.mongodb.tls.enabled .Values.mongodb.tls.certManager.enabled }}
{{- $commonName := (printf "*.%s-svc.%s.svc.%s" (include "mongodb.fullname" .) .Release.Namespace .Values.clusterDomain) }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "mongodb.fullname" . }}-self-signed-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mongodb.fullname" . }}-self-signed-ca-tls
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: {{ $commonName | quote }}
  secretName: {{ include "mongodb.fullname" . }}-self-signed-ca-tls
  duration: {{ .Values.mongodb.tls.duration }}
  renewBefore: {{ .Values.mongodb.tls.renewBefore }}
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: {{ include "mongodb.fullname" . }}-self-signed-issuer
    kind: Issuer
  dnsNames:
    - {{ $commonName | quote }}
    {{- range .Values.mongodb.tls.certManager.dnsNames }}
    - {{ . | quote }}
    {{- end }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "mongodb.fullname" . }}-ca-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca:
    secretName: {{ include "mongodb.fullname" . }}-self-signed-ca-tls
{{- end }}